[versions]

# general (local snapshot: "LOCAL-SNAPSHOT")
# --

# plugins only
kmpicon =                   "1.0.0"
kmpdevtools =               "7.9.7" # use the "devTools" task to change the version

# demos
democomposables =           "1.0.5"

[plugins]

# plugins only
kmpdevtools-buildplugin =           { id = "io.github.mflisar.kmpdevtools.plugins-build-gradle",        version.ref = "kmpdevtools" }
kmpicon-plugin =                    { id = "io.github.mflisar.kmpicon.plugin",                          version.ref = "kmpicon" }

[libraries]

# demos
democomposables =                               { module = "io.github.mflisar.democomposables:library",                             version.ref = "democomposables" }